branhc testing shouldn't need to remove any gateways

diff --git a/.github/workflows/branchtest.yml b/.github/workflows/branchtest.yml
--- a/.github/workflows/branchtest.yml
+++ b/.github/workflows/branchtest.yml
@@ -51,33 +51,33 @@ jobs:
         run: |
           curl -L ${{ inputs.api }}/api/users/adm/createsuperadmin -d '{"username":"${{ secrets.NM_USER }}","password":"${{ secrets.NM_PASSWORD }}"}'
 
-  clean:
-    name: remove all gateways
-    runs-on: ubuntu-latest
-    steps:
-      - name: get binary
-        run: |
-          mkdir bin
-          wget -O bin/test fileserver.clustercat.com/testing/test
-      - name: run tests
-        id: clean
-        run: |
-          chmod +x bin/test
-          bin/test clean
-        env:
-          DIGITALOCEAN_TOKEN: ${{ secrets.TESTING_DO_TOKEN  }}
-          KEY: ${{ secrets.TESTING_SSH_KEY }}
-          TAG: ${{ inputs.tag }}
-          NETWORK: ${{ inputs.network}}
-          MASTERKEY: ${{ inputs.masterkey }}
-          API: ${{ inputs.api }}
-      - name: save logs
-        if: success() || failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: clean
-          path: /tmp/clean.log
-          retention-days: 3
+  # clean:
+  #   name: remove all gateways
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: get binary
+  #       run: |
+  #         mkdir bin
+  #         wget -O bin/test fileserver.clustercat.com/testing/test
+  #     - name: run tests
+  #       id: clean
+  #       run: |
+  #         chmod +x bin/test
+  #         bin/test clean
+  #       env:
+  #         DIGITALOCEAN_TOKEN: ${{ secrets.TESTING_DO_TOKEN  }}
+  #         KEY: ${{ secrets.TESTING_SSH_KEY }}
+  #         TAG: ${{ inputs.tag }}
+  #         NETWORK: ${{ inputs.network}}
+  #         MASTERKEY: ${{ inputs.masterkey }}
+  #         API: ${{ inputs.api }}
+  #     - name: save logs
+  #       if: success() || failure()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: clean
+  #         path: /tmp/clean.log
+  #         retention-days: 3
 
 
   initial-ping:
